version: 1
language: kotlin
branches:                # 브랜치 필터링 옵션 추가
  include:
    - "auto-pr*"             # 브랜치 이름이 "111"로 시작하는 모든 브랜치를 포함
  exclude: []            # 필요시 제외할 브랜치 패턴을 추가할 수 있음

review:
  enabled: true           # 코드 리뷰 기능 활성화
  rules:
    complexity:
      max: 15             # 허용 가능한 최대 복잡도 (예: 15로 설정)
    max-line-length:
      max: 120            # 한 줄의 최대 길이 (예: 120자)
    no-unused-imports: error  # 사용하지 않는 import가 있으면 에러 처리
    naming:
      class-name: error        # 클래스 명명 규칙 위반 시 에러
      method-name: warn        # 메서드 명명 규칙 위반 시 경고
    duplicate-code:
      enabled: true            # 중복 코드 검사 활성화
      threshold: 10            # 중복 코드 감지 기준 (예: 10줄 이상)
    style:
      enforce-braces: error    # 조건문, 반복문 등에서 중괄호 사용 강제
    formatting:
      indent: 4                # 들여쓰기 규칙 (예: 공백 4칸)
    exclude:
      - 'build/**'
      - 'out/**'
      - 'generated/**'
